"""empty message

Revision ID: 308408039701
Revises: 8381bb9defaa
Create Date: 2023-10-02 16:57:12.654270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308408039701'
down_revision = '8381bb9defaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_list', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
