"""empty message

Revision ID: 8381bb9defaa
Revises: 5466941c295a
Create Date: 2023-09-29 18:06:00.789100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8381bb9defaa'
down_revision = '5466941c295a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('current_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('all_time_high_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('market_cap', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto', schema=None) as batch_op:
        batch_op.drop_column('market_cap')
        batch_op.drop_column('all_time_high_price')
        batch_op.drop_column('current_price')
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
