"""empty message

Revision ID: cb341965bfe1
Revises: d8bb55b3291d
Create Date: 2023-10-23 23:32:04.582329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb341965bfe1'
down_revision = 'd8bb55b3291d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reset_request')
    # ### end Alembic commands ###
